AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  genbot-retrieve

  Retrieves generated image

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  HttpApi:
    AccessLogSettings:
      DestinationArn: !GetAtt GenBotRetrieveFunctionApiLogGroup.Arn
      # Common Log Format (CLF) - https://httpd.apache.org/docs/current/logs.html#common
      Format: $context.identity.sourceIp - - [$context.requestTime] "$context.httpMethod $context.routeKey $context.protocol" $context.status $context.responseLength $context.requestId $context.extendedRequestId
    Tags:
      Application: bots
  Function:
    Runtime: nodejs22.x
    Timeout: 5
    MemorySize: 512
    Tags:
      Application: bots

Resources:
  GenBotRetrieveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: genbot-retrieve
      CodeUri: ./
      Handler: retrieve.handler
      Description: Retrieves generated image
      Policies:
        - Statement:
            - Sid: AllowImageBucketObjectGet
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: 'arn:aws:s3:::case-consulting-mgmt-genbot-images/*'
      Events:
        GenBot:
          Type: HttpApi # More info about HTTP API Event Source: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
          Properties:
            Path: /{imagePath+}
            Method: get
  GenBotRetrieveFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GenBotRetrieveFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${GenBotRetrieveFunction}
      RetentionInDays: 30
  GenBotRetrieveFunctionApiLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GenBotRetrieveFunction
    Properties:
      LogGroupName: !Sub /aws/api-gateway/${GenBotRetrieveFunction}
      RetentionInDays: 30

Outputs:
  # ServerlessHttpApi is an implicit HTTP API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GenBotRetrieveApi:
    Description: 'GenBot HTTP API Endpoint URL'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: GenBotRetrieveApi
  GenBotRetrieveFunction:
    Description: 'GenBot Lambda Function ARN'
    Value: !GetAtt GenBotRetrieveFunction.Arn
  GenBotRetrieveFunctionIamRole:
    Description: 'Implicit IAM Role created for GenBot function'
    Value: !GetAtt GenBotRetrieveFunctionRole.Arn
