AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  genbot

  Uses generative AI to create image based on given prompt

# More info about Globals: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
Globals:
  HttpApi:
    AccessLogSettings:
      DestinationArn: !GetAtt GenBotFunctionApiLogGroup.Arn
      # Common Log Format (CLF) - https://httpd.apache.org/docs/current/logs.html#common
      Format: $context.identity.sourceIp - - [$context.requestTime] "$context.httpMethod $context.routeKey $context.protocol" $context.status $context.responseLength $context.requestId $context.extendedRequestId
    Tags:
      Application: bots
  Function:
    Runtime: nodejs22.x
    Tags:
      Application: bots

Resources:
  GenBotImagesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: case-consulting-mgmt-genbot-images
      LifecycleConfiguration:
        Rules:
          - Id: Remove old images
            ExpirationInDays: 183 # ~6 months
            Status: Enabled
      Tags:
        - Key: Application
          Value: bots
  GenBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    DependsOn:
      - GenBotImagesBucket
      - GenBotRetrieveFunctionUrl
    Properties:
      FunctionName: genbot
      CodeUri: ./
      Handler: generate.handler
      Description: Uses generative AI to create image based on given prompt
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          companyId: '{{resolve:ssm:/Basecamp/CompanyID:1}}'
          retrieveApi: !GetAtt GenBotRetrieveFunctionUrl.FunctionUrl
      Policies:
        - Statement:
            - Sid: InvokeFoundationModel
              Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.nova-canvas-v1:0
        - Statement:
            - Sid: AllowImageBucketObjectPut
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: 'arn:aws:s3:::case-consulting-mgmt-genbot-images/*'
      Events:
        GenBot:
          Type: HttpApi # More info about HTTP API Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-httpapi.html
          Properties:
            Path: /
            Method: post
  GenBotFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GenBotFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${GenBotFunction}
      RetentionInDays: 30
  GenBotFunctionApiLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GenBotFunction
    Properties:
      LogGroupName: !Sub /aws/api-gateway/${GenBotFunction}
      RetentionInDays: 30
  GenBotRetrieveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    DependsOn:
      - GenBotImagesBucket
    Properties:
      FunctionName: genbot-retrieve
      CodeUri: ./
      Handler: retrieve.handler
      Description: Retrieves generated image
      Timeout: 5
      MemorySize: 256
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - Statement:
            - Sid: AllowImageBucketObjectGet
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - 'arn:aws:s3:::case-consulting-mgmt-genbot-images'
                - 'arn:aws:s3:::case-consulting-mgmt-genbot-images/*'
  GenBotRetrieveFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GenBotRetrieveFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${GenBotRetrieveFunction}
      RetentionInDays: 30

Outputs:
  # ServerlessHttpApi is an implicit HTTP API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GenBotApi:
    Description: 'GenBot HTTP API Endpoint URL'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
  GenBotFunction:
    Description: 'GenBot Lambda Function ARN'
    Value: !GetAtt GenBotFunction.Arn
  GenBotFunctionIamRole:
    Description: 'Implicit IAM Role created for GenBot function'
    Value: !GetAtt GenBotFunctionRole.Arn

  GenBotRetrieveApi:
    Description: 'GenBot Retrieve Lambda Function URL'
    Value: !GetAtt GenBotRetrieveFunctionUrl.FunctionUrl
  GenBotRetrieveFunction:
    Description: 'GenBot Retrieve Lambda Function ARN'
    Value: !GetAtt GenBotRetrieveFunction.Arn
  GenBotRetrieveFunctionIamRole:
    Description: 'Implicit IAM Role created for GenBot Retrieve function'
    Value: !GetAtt GenBotRetrieveFunctionRole.Arn

  GenBotImagesBucket:
    Description: 'GenBot Images Bucket Name'
    Value: !Ref GenBotImagesBucket
