AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  genbot-retrieve

  Retrieves generated image

# More info about Globals: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 5
    MemorySize: 256
    Tags:
      Application: bots

Resources:
  GenBotRetrieveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      FunctionName: genbot-retrieve
      CodeUri: ./
      Handler: retrieve.handler
      Description: Retrieves generated image
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - Statement:
            - Sid: AllowImageBucketObjectGet
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - 'arn:aws:s3:::case-consulting-mgmt-genbot-images'
                - 'arn:aws:s3:::case-consulting-mgmt-genbot-images/*'
  GenBotRetrieveFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GenBotRetrieveFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${GenBotRetrieveFunction}
      RetentionInDays: 30

Outputs:
  GenBotRetrieveApi:
    Description: 'GenBot Retrieve Lambda Function URL'
    Value: !GetAtt GenBotRetrieveFunctionUrl.FunctionUrl
    Export:
      Name: GenBotRetrieveApi
  GenBotRetrieveFunction:
    Description: 'GenBot Retrieve Lambda Function ARN'
    Value: !GetAtt GenBotRetrieveFunction.Arn
  GenBotRetrieveFunctionIamRole:
    Description: 'Implicit IAM Role created for GenBot Retrieve function'
    Value: !GetAtt GenBotRetrieveFunctionRole.Arn
